module.exports.places = [
    
    "IIT, Delhi (Delhi)",
    "IIT, Bombay (Mumbai)",
    "IIT, Kharagpur (Kharagpur)",
    "IIT, Kanpur (Kanpur)",
    "Birla Institute Of Technology & Science (Pilani)",
    "NIT, Karnataka (Mangalore)",
    "College Of Engineering, Guindy (Chennai)",
    "Netaji Subhas Institute Of Technology* (New Delhi)",
    "VIT University (Vellore)",
    "College Of Engineering, Pune (Pune)",
    "IIIT, Hyderabad (Hyderabad)",
    "IIIT, Allahabad (Allahabad)",
    "Indian Institute Of Technology (Indian School Of Mines), Dhanbad (Dhanbad)",
    "Delhi Technological University (New-Delhi)",
    "Manipal Institue Of Technology (Manipal)",
    "University Institute Of Engineering, Chandigarh University (Chandigarh)",
    "PSG College of Technology (Coimbatore)",
    "Visvesvaraya National Institute Of Technology (Nagpur)",
    "Thapar University (Patiala)",
    "M.S. Ramaiah Institute Of Technology (Bangalore)",
    "Birla Institute Of Technology (Ranchi)",
    "The National Institute Of Engineering (Mysore)",
    "University College Of Engineering (Hyderabad)",
    "Sri Sivasubramaniya Nadar College of Engineering (Kalavakkam)",
    "B.I.T. Sindri (Dhanbad)",
    "Institute Of Technology (Ahmedabad)",
    "SRM Engineering College (Chennai)",
    "Government College Of Engineering (Amravati)",
    "SVKM's NMIMS-Mukesh Patel School Of Technology Management & Engineering (Mumbai)",
    "Mepco Schlenk Engineering College (Sivakasi)",
    "Thiagarajar College Of Engineering (Madurai)",
    "Chaitanya Bharathi Institute Of Technology (Hyderabad)",
    "Dwarkadas J. Sanghvi College Of Engineering (Mumbai)",
    "Rungta College Of Engineering And Technology (Bhilai)",
    "Guru Nanak Dev Engineering College (Ludhiana)",
    "Zakir Husain College Of Engineering & Technology, Aligarh (Aligarh)",
    "Govt. Model Engineering College (Cochin)",
    "MIT College Of Engineering (Pune)",
    "PES University (Bangalore)",
    "KLE Dr M.S Sheshgiri College Of Engineering And Technology (Belgaum)",
    "Bannari Amman Institute Of Technology (Erode)",
    "Symbiosis Institute Of Technology (Pune)",
    "BMS Institute Of Technology & Management (Bangalore)",
    "BMS College Of Engineering (Bangalore)",
    "Bharati Vidyapeeth University College Of Engineering (Pune)",
    "Jawaharlal Nehru National College Of Engineering (Shimoga)",
    "K L University (Guntur)",
    "Galgotias College Of Engineering And Technology (Noida)",
    "Shri Ramdeobaba College Of Engineering And Management (Nagpur)",
    "Sri Sairam Engineering College (Chennai)",
    "Cummins College of Engineering for Women (Pune)",
    "Faculty Of Engineering, DIT University (Dehradun)",
    "Sanjivani Rural Education Society's College Of Engineering (Ahmednagar)",
    "SDM College Of Engineering & Technology (Dharwad)",
    "Pimpri Chinchwad College Of Engineering (Pune)",
    "M V J College Of Engineering (Bangalore)",
    "Sir M Visvesvaraya Institute Of Technology (Bangalore)",
    "The Northcap University (Gurgaon)",
    "Rajagiri School Of Engineering & Technology (Ernakulam)",
    "Indraprastha Institute Of Information Technology Delhi (New Delhi)",
    "National Institute Of Science & Technology (Berhampur)",
    "Muffakham Jah College Of Engineering And Technology (Hyderabad)",
    "JSS Academy Of Technical Education (Bangalore)",
    "Army Institute Of Technology (Pune)",
    "Amity School Of Engineering & Technology (Noida)",
    "Lovely Professional University (Phagwara)",
    "JIS College Of Engineering (Kalyani, West Bengal)",
    "IMS Engineering College (Ghaziabad)",
    "P.E.S. College Of Engineering (Mandya)",
    "Lakshmi Narain College Of Technology (Bhopal)",
    "Sikkim Manipal Institute Of Technology (Sikkim)",
    "Ganeshi Lal Bajaj Institute Of Technology & Management (Noida)",
    "SCMS School Of Engineering & Technology (Ernakulam)",
    "Kongu Engineering College (Erode)",
    "K.S.R. College Of Enginnering (Thiruchengode)",
    "Maharashtra Institute Of Technology (Aurangabad)",
    "Sri Sairam College of Engineering (Bangalore)",
    "J.B. Institute Of Technology (Dehradun)",
    "Jaipur Engineering College And Research Center (Jaipur)",
    "R.M.K. Engineering College (Kavaripettai)",
    "S.A. Engineering College (Chennai)",
    "University Institute Of Engineering & Technology, Panjab University (Chandigarh)",
    "Kuppam Engineering College (Kuppam)",
    "Asia Pacific Institute of Information Technology (APIIT SD) (Panipat)",
    "Malla Reddy College of Engineering & Technology (Secunderabd)",
    "CVR College Of Engineering (Hyderabad)",
    "Veltech High Tech Dr .Rangarajan Dr. Sakunthala Engineering College (Chennai)",
    "Vishwakarma Institute of Technology (Pune)",
    "M.S. Engineering College (Bangalore)",
    "R.M.D. Engineering College (Thiruvallur)",
    "Rajarambapu Institute Of Technology (Sangli)",
    "Shri Vishnu Engineering College For Women (Bhimavaram)",
    "Government College Of Engineering (Karad)",
    "Institute Of Engineering & Technology, J.K.Lakshmipat University (Jaipur)",
    "Shri Shankaracharya Technical Campus Bhilai (Bhilai)",
    "IES College Of Technology (Bhopal)",
    "Madhav Institute of Technology & Science (Gwalior)",
    "KIET Group Of Institutions (Ghaziabad)",
    "BRACT'S Vishwakarma Institute of Information Technology (Pune)",
    "KLS Gogte Institute Of Technology (Belagavi)"
]

